# Generated by Django 3.1 on 2020-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='toys',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
