# Generated by Django 3.1 on 2020-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_finch_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='toys',
        ),
        migrations.AddField(
            model_name='finch',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
